// DatingApp.SPA/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { Http } from '@angular/http';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  registerMode = false;
  values: any;

  constructor(private http: Http) { }

  ngOnInit() {
  }

  registerToggle() {
    this.registerMode = true;
  }

  cancelRegisterMode(registerMode: boolean) {
      this.registerMode = registerMode;
  }

}

<div  *ngIf="!registerMode" style="text-align: center">
  <h1>
    Find your match!
  </h1>
<p class="lead">Come on in to view your matcher.. All you need to do is sign up!</p>

<div class="text-center">
  <button class="btn btn-primary btn-lg"(click)="registerToggle()">Register</button>
  <button class="btn btn-info btn-lg">Learn more</button>
</div>

</div>

<div *ngIf="registerMode" class="containter">
  <div class="col-md-4 col-md-offset-4">
    <app-register (cancelRegister)="cancelRegisterMode($event)"></app-register>
  </div>
</div>

// dating-app/src/components/home/home.tsx
import { useCallback } from "react";
import { Button, Container } from "react-bootstrap";
import { useNavigate } from "react-router-dom";

export default function Home() {
  const navigate = useNavigate();

  const goToForm = useCallback(() => navigate("/register"), [navigate]);

  return (
    <Container className="mt-5" style={{ marginTop: 100, width: "50%" }}>
      <div style={{ textAlign: "center" }}>
        <h1>Find your match</h1>
        <p className="lead">
          Come on in to view your matches... all you need to do is sign up!
        </p>
        <div className="text-center">
          <Button variant="primary" onClick={goToForm}>
            Register
          </Button>
          <Button variant="info">Learn more</Button>
        </div>
      </div>
    </Container>
  );
}
