// DatingApp.SPA/src/app/nav/nav.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from '../_services/auth.service';
import { AlertifyService } from '../_services/alertify.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-nav',
  templateUrl: './nav.component.html',
  styleUrls: ['./nav.component.css']
})
export class NavComponent implements OnInit {

  model: any = {};


  constructor(private authService: AuthService, private alertify: AlertifyService, private router: Router) { }

  ngOnInit() {
  }

  login() {
    this.authService.login(this.model).subscribe(data => {
      this.alertify.success('logged in successfully');
    }, error => {
      this.alertify.error('Failed to log in');
    }, () => {
      this.router.navigate(['/members']);
    });
  }

  logout() {
    this.authService.userToken = null;
    localStorage.removeItem('token');
    this.alertify.message('logged out');
    this.router.navigate(['/home']);
  }

  loggedIn() {
    return this.authService.loggedin();
  }

}

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" [routerLink]="['/home']">Dating App</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav" *ngIf="loggedIn()">
        <li routerLinkActive="active" ><a [routerLink]="['/members']" >Matches</a></li>
        <li routerLinkActive="active"><a [routerLink]="['/lists']">Lists</a></li>
        <li routerLinkActive="active"><a [routerLink]="['/messages']">Messages</a></li>
      </ul>

      <form *ngIf="!loggedIn()" #loginForm="ngForm" class="navbar-form navbar-right" (ngSubmit)="login()">
        <div class="form-group">
          <input type="text" #username="ngModel" placeholder="Username" class="form-control" required  name="username" [(ngModel)]="model.username">
        </div>
        <div class="form-group">
          <input type="password" #password="ngModel" placeholder="Password" class="form-control" required name="password" [(ngModel)]="model.password">
        </div>
        <button type="submit" [disabled]="!loginForm.valid" class="btn btn-success">Sign in</button>
      </form>

      <ul *ngIf="loggedIn()" class="nav navbar-nav navbar-right">
        <li class="dropdown" dropdown>
          <a (click)=false class="dropdown-toggle" dropdownToggle>Welcome {{ authService.decodedToken?.unique_name | titlecase}} <span class="caret"></span></a>
          <ul class="dropdown-menu" *dropdownMenu>
            <li><a href="#"><i class="fa fa-user"></i> Edit Profile</a></li>
            <li role="separator" class="divider"></li>
            <li><a (click)="logout()"><i class="fa fa-sign-out"></i>Logout</a></li>
          </ul>
        </li>
      </ul>

    </div><!--/.navbar-collapse -->
  </div>
</nav>

// dating-app/src/components/nav/nav.tsx
import { useMutation } from "@apollo/client";
import { useCallback, useEffect, useState } from "react";
import { Container, Nav, NavDropdown, Navbar } from "react-bootstrap";
import { useForm } from "react-hook-form";
import { LOGIN } from "../gql/navQueries";
import { NavLink } from "react-router-dom";

interface AuthenticateFormData {
  username: string;
  password: string;
}

interface AuthenticateUserResult {
  login: {
    username: string;
    token: string;
  };
}

interface AuthenticateUserVariables {
  loginDto: {
    username: string;
    password: string;
  };
}

export function NavBar() {
  const { register, handleSubmit } = useForm<AuthenticateFormData>();

  const [loggedIn, setLoggedIn] = useState(false);
  const [username, setUsername] = useState("");

  useEffect(() => {
    const auth = localStorage.getItem("AUTH_TOKEN");
    if (auth) {
      setLoggedIn(true);
      const userObj = JSON.parse(auth);
      const capitalizedName =
        userObj.username.charAt(0).toUpperCase() + userObj.username.slice(1);
      setUsername(capitalizedName);
    }
  }, []);

  const [authenticate, { loading }] = useMutation<
    AuthenticateUserResult,
    AuthenticateUserVariables
  >(LOGIN);

  const onSubmit = async (formData: AuthenticateFormData) => {
    try {
      const { data } = await authenticate({
        variables: {
          loginDto: {
            username: formData.username,
            password: formData.password,
          },
        },
      });

      const token = data?.login.token;
      if (token) {
        localStorage.setItem("AUTH_TOKEN", JSON.stringify(data?.login));
        const capitalizedName =
          data?.login.username.charAt(0).toUpperCase() +
          data?.login.username.slice(1);
        setUsername(capitalizedName);
        setLoggedIn(true);
      }

      console.log("User authenticated successfully: ", data);
    } catch (error) {
      console.log("Error authenticating user: ", error);
    }
  };

  const logout = useCallback(() => {
    localStorage.removeItem("AUTH_TOKEN");
    setUsername("");
  }, []);

  return (
    <Navbar variant="dark" bg="primary" expand="md">
      <Container>
        <Navbar.Brand href="/">Dating App</Navbar.Brand>
        {loggedIn ? (
          <>
            <Nav
              className="me-auto my-2 my-lg-0"
              style={{ maxHeight: "100px" }}
            >
              <NavLink
                to={"/members"}
                className={({ isActive }) =>
                  isActive ? "nav-link active" : "nav-link"
                }
              >
                Matches
              </NavLink>
              <NavLink
                to="/lists"
                className={({ isActive }) =>
                  isActive ? "nav-link active" : "nav-link"
                }
              >
                Lists
              </NavLink>
              <NavLink
                to="/messages"
                className={({ isActive }) =>
                  isActive ? "nav-link active" : "nav-link"
                }
              >
                Messages
              </NavLink>
            </Nav>
            <Navbar.Collapse
              style={{
                display: "flex",
                flexWrap: "inherit",
                alignItems: "flex-end",
                justifyContent: "flex-end",
              }}
            >
              <Nav>
                <NavDropdown
                  id="nav-dropdown-dark-example"
                  title={`Welcome ${username}`}
                >
                  <NavDropdown.Item href="/">Edit profile</NavDropdown.Item>
                  <NavDropdown.Item onClick={logout} href="/">
                    Logout
                  </NavDropdown.Item>
                </NavDropdown>
              </Nav>
            </Navbar.Collapse>
          </>
        ) : (
          <form
            autoComplete="off"
            className="d-flex"
            onSubmit={handleSubmit(onSubmit)}
          >
            <input
              className="form-control me-2"
              type="text"
              placeholder="Username"
              {...register("username", {})}
            />
            <input
              className="form-control me-2"
              type="password"
              placeholder="Password"
              {...register("password", {})}
            />
            <button
              className="btn btn-success"
              disabled={loading}
              type="submit"
            >
              {loading ? "Loading..." : "Login"}
            </button>
          </form>
        )}
      </Container>
    </Navbar>
  );
}
