// dating-app/src/components/Members/MemberDetail.tsx
import { useCallback, useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { Member } from "../../models/Member";
import { Tab, Tabs } from "react-bootstrap";
import PhotoGallery from "./components/PhotoGallery/PhotoGallery";
import { useGetMember } from "./hooks";

export default function MemberDetail() {
  const { username } = useParams();

  const [member, setMember] = useState<Member>();
  const { getMember: getMemberHook } = useGetMember(username);

  const memberHookFetch = useCallback(async () => {
    const memberHook = await getMemberHook();
    setMember(memberHook);
    console.log("hook: ", memberHook);
  }, [getMemberHook]);

  useEffect(() => {
    memberHookFetch();
  }, [memberHookFetch]);

  if (!username) {
    return <div>Member not found....</div>;
  }

  const renderTabs = (member: Member) => {
    return (
      <Tabs defaultActiveKey="about" className="mb-3">
        <Tab eventKey="about" title={`About ${member.knownAs}`}>
          <h4>Description</h4>
          <p>{member.introduction}</p>
          <h4>Looking for</h4>
          <p>{member.interests}</p>
        </Tab>
        <Tab eventKey="profile" title="Interests">
          <h4>Interests</h4>
          <p>{member.interests}</p>
        </Tab>
        <Tab eventKey="photo" title="Photos">
          <PhotoGallery photos={member.photos} />
        </Tab>
        <Tab eventKey="messages" title="Messages">
          Tab content for Messages
        </Tab>
      </Tabs>
    );
  };

  return (
    <div className="row" style={{ paddingLeft: 30, paddingTop: 25 }}>
      {member ? (
        <>
          <div className="col-4">
            <div className="card">
              <img
                src={member.photoUrl || "../../assets/user.png"}
                alt={member.knownAs}
                className="card-img-top img-thumbnail"
                style={{ margin: 25, width: "85%", height: "85%" }}
              />
              <div
                style={{
                  paddingTop: 0,
                  paddingBottom: 0,
                  paddingLeft: 25,
                  paddingRight: 25,
                }}
              >
                <div>
                  <strong>Location: </strong>
                  <p>{member.country}</p>
                </div>
                <div>
                  <strong>Age: </strong>
                  <p>{member.age}</p>
                </div>
                {member.lastActive ? (
                  <div>
                    <strong>Last Active: </strong>
                    <p>{new Date(member.lastActive).toDateString()}</p>
                  </div>
                ) : null}
                {member.created ? (
                  <div>
                    <strong>Member since: </strong>
                    <p>{new Date(member.created).toDateString()}</p>
                  </div>
                ) : null}
              </div>
              <div
                style={{
                  paddingTop: 10,
                  paddingBottom: 10,
                  paddingLeft: 15,
                  paddingRight: 15,
                  borderTop: "none",
                  backgroundColor: "#FFF",
                }}
              >
                <div className="btn-group d-flex">
                  <button className="btn btn-primary">Like</button>
                  <button className="btn btn-success">Messages</button>
                </div>
              </div>
            </div>
          </div>
          <div className="col-8">{renderTabs(member)}</div>
        </>
      ) : null}
    </div>
  );
}

// client/src/app/members/member-detail/member-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import {
  NgxGalleryAnimation,
  NgxGalleryImage,
  NgxGalleryOptions,
} from '@kolkov/ngx-gallery';
import { Member } from 'src/app/_models/member';
import { MembersService } from 'src/app/_services/members.service';

@Component({
  selector: 'app-member-detail',
  templateUrl: './member-detail.component.html',
  styleUrls: ['./member-detail.component.css'],
})
export class MemberDetailComponent implements OnInit {
  member: Member | undefined;
  galleryOptions: NgxGalleryOptions[] = [];
  galleryImages: NgxGalleryImage[] = [];

  constructor(
    private memberService: MembersService,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this.loadMember();

    this.galleryOptions = [
      {
        width: '500px',
        height: '500px',
        imagePercent: 100,
        thumbnailsColumns: 4,
        imageAnimation: NgxGalleryAnimation.Slide,
        preview: false,
      },
    ];

    this.galleryImages = this.getImages();
  }

  getImages() {
    if (!this.member) return [];

    const imageUrls = [];
    for (const photo of this.member.photos) {
      imageUrls.push({
        small: photo.url,
        medium: photo.url,
        big: photo.url,
      });
    }

    return imageUrls;
  }

  loadMember() {
    const userName = this.route.snapshot.paramMap.get('username');

    if (!userName) return;

    this.memberService.getMember(userName).subscribe({
      next: (member) => {
        this.member = member;
        this.galleryImages = this.getImages();
      },
    });
  }
}

<div class="row" *ngIf="member">
  <div class="col-4">
    <div class="card">
      <img src="{{member.photoUrl || './assets/user.png'}}" alt="{{member.knownAs}}" class="card-img-top img-thumbnail">
      <div class="card-body">
        <div>
          <strong>Location: </strong>
          <p>{{member.city}}, {{member.country}}</p>
        </div>
        <div>
          <strong>Age: </strong>
          <p>{{member.age}}</p>
        </div>
        <div>
          <strong>Last active: </strong>
          <p>{{member.lastActive}}</p>
        </div>
        <div>
          <strong>Member since: </strong>
          <p>{{member.created}}</p>
        </div>
      </div>
      <div class="card-footer">
        <div class="btn-group d-flex">
          <button class="btn btn-primary">Like</button>
          <button class="btn btn-success">Messages</button>
        </div>
      </div>

    </div>
  </div>
  <div class="col-8">
    <tabset class="member-tabset">
      <tab heading="About {{member.knownAs}}">
        <h4>Description</h4>
        <p>{{member.introduction}}</p>
        <h4>Looking for</h4>
        <p>{{member.interests}}</p>
      </tab>
      <tab heading="Interests">
        <h4>Interests</h4>
        <p>{{member.interests}}</p>
      </tab>
      <tab heading="Photos">
        <ngx-gallery [options]="galleryOptions" [images]="galleryImages" class="ngx-gallery"></ngx-gallery>
      </tab>
      <tab heading="Messages">
        <p>Messages here</p>
      </tab>
    </tabset>
  </div>
</div>
