// dating-app/src/components/home/home.tsx
import { useCallback } from "react";
import { Button, Container } from "react-bootstrap";
import { useNavigate } from "react-router-dom";

export default function Home() {
  const navigate = useNavigate();

  const goToForm = useCallback(() => navigate("/register"), [navigate]);

  return (
    <Container className="mt-5" style={{ marginTop: 100, width: "50%" }}>
      <div style={{ textAlign: "center" }}>
        <h1>Find your match</h1>
        <p className="lead">
          Come on in to view your matches... all you need to do is sign up!
        </p>
        <div className="text-center">
          <Button variant="primary" onClick={goToForm}>
            Register
          </Button>
          <Button variant="info">Learn more</Button>
        </div>
      </div>
    </Container>
  );
}

// client/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { Apollo } from 'apollo-angular';
import { Observable, map, of } from 'rxjs';
import { GET_USERS } from '../gql/users';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
export class HomeComponent implements OnInit {
  registerMode = false;
  users: any;

  constructor() {}

  ngOnInit(): void {
    // this.getMembersGql();
  }

  registerToggle() {
    this.registerMode = !this.registerMode;
  }

  cancelRegisterMode(event: boolean) {
    this.registerMode = event;
  }
}

<div class="container mt-5">
  <div *ngIf="!registerMode" style="text-align: center;">
    <h1>Find your match</h1>
    <p class="lead">Come on in to view your matches... all you need to do is sign up!</p>
    <div class="text-center">
      <button (click)="registerToggle()" class="btn btn-primary btn-lg me-2">
        Register
      </button>
      <button class="btn btn-info btn-lg me-2">
        Learn more
      </button>
    </div>
  </div>

  <div *ngIf="registerMode" class="container">
    <div class="row justify-content-center">
      <div class="col-4">
        <app-register (cancelRegister)="cancelRegisterMode($event)"></app-register>
      </div>
    </div>
  </div>
</div>
