// DatingApp.SPA/src/app/members/member-edit/member-edit.component.ts
import { Component, OnInit, ViewChild, HostListener } from '@angular/core';
import { User } from '../../_models/User';
import { ActivatedRoute } from '../../../../node_modules/@angular/router';
import { AlertifyService } from '../../_services/alertify.service';
import { NgForm } from '../../../../node_modules/@angular/forms';
import { UserService } from '../../_services/user.service';
import { AuthService } from '../../_services/auth.service';

@Component({
  selector: 'app-member-edit',
  templateUrl: './member-edit.component.html',
  styleUrls: ['./member-edit.component.css']
})
export class MemberEditComponent implements OnInit {
  @ViewChild('editForm') editForm: NgForm;
  user: User;
  @HostListener('window:beforeunload', ['$event'])
  unloadNotification($event: any) {
    if (this.editForm.dirty) {
      $event.returnValue = true;
    }
  }

  constructor(private route: ActivatedRoute, private alertify: AlertifyService,
    private userService: UserService, private authService: AuthService) { }

  ngOnInit() {
    this.route.data.subscribe(data => {
      this.user = data['user'];
    });
  }

  updateUser() {
    this.userService.updateUser(this.authService.decodedToken.nameid, this.user).subscribe(next => {
      this.alertify.success('Profile updated successfully');
      this.editForm.reset(this.user);
    }, error => {
      this.alertify.error(error);
    });
  }

}

<div class="container">
  <div class="row">
    <div class="col-sm-4">
        <h1>Your Profile</h1>
    </div>

    <div class="col-sm-8">
      <div *ngIf="editForm.dirty" class="alert alert-info">
        <strong>Information:</strong> You have made changes. Any unsaved changes will be lost!
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4">
      <div class="panel panel-default">
        <img class="profile-image thumbnail" src="{{user.photoUrl}}" alt="{{user.knownAs}}">
        <div class="panel-body">
          <div>
            <strong>Location:</strong>
            <p>{{user.city}}, {{user.country}}</p>
          </div>

          <div>
            <strong>Age:</strong>
            <p>{{user.age}}</p>
          </div>

          <div>
            <strong>Last Active:</strong>
            <p>{{user.lastactive}}</p>
          </div>

          <div>
            <strong>Member Since:</strong>
            <p>{{user.created}}</p>
          </div>
        </div>

        <div class="panel-footer">
          <button [disabled]= "!editForm.dirty" form="editForm" class="btn btn-success btn-block">Save Changes</button>
        </div>
      </div>
    </div>
    <div class="col-sm-8">
      <div class="tab-panel">
          <tabset class="member-tabset">
              <tab heading="Edit Profile">
                <form #editForm="ngForm" id="editForm" (ngSubmit)="updateUser()">
                    <h4>Description</h4>
                    <textarea name="introduction" rows="6" class="form-control" [(ngModel)]="user.introduction"></textarea>
                    <h4>Looking for:</h4>
                    <textarea name="lookingFor" rows="6" class="form-control" [(ngModel)]="user.lookingFor"></textarea>
                    <h4>Interests:</h4>
                    <textarea name="interests" rows="6" class="form-control" [(ngModel)]="user.interests"></textarea>
                    <h4>Location Details</h4>
                    <div class="form-inline">
                      <label for="city">City</label>
                      <input type="text" class="form-control" name="city" [(ngModel)]="user.city">
                      <label for="country">Country</label>
                      <input type="text" class="form-control" name="country" [(ngModel)]="user.country">
                    </div>
                </form>
              </tab>
      
              <tab heading="Edit Photos">
                <p>Photo edit will go here</p>
              </tab>
            </tabset>
      </div>
      
    </div>
  </div>

</div>

// dating-app/src/components/Members/MemberEdit.tsx
import { Tab, Tabs } from "react-bootstrap";
import { Member } from "../../models/Member";
import { useLocation } from "react-router-dom";
import { useCallback, useEffect, useState } from "react";
import { useGetMember } from "./hooks";
import { useForm } from "react-hook-form";

interface EditFormData {
  city: string;
  country: string;
  description: string;
  lookingFor: string;
}

export default function MemberEdit() {
  const { state } = useLocation();
  const { username } = state;

  const {
    register,
    handleSubmit,
    formState: { isDirty },
  } = useForm<EditFormData>();

  const [member, setMember] = useState<Member>();

  const { getMember } = useGetMember(username);

  const memberHookFetch = useCallback(async () => {
    const memberHook = await getMember();
    setMember(memberHook);
    console.log("hook: ", memberHook);
    setMember(memberHook);
  }, [getMember]);

  useEffect(() => {
    memberHookFetch();
  }, [memberHookFetch]);

  const onSubmit = useCallback((formValues: any) => {
    console.log("values: ", formValues);
  }, []);

  if (!username) return <div></div>;

  const renderTabs = (member: Member) => {
    return (
      <Tabs defaultActiveKey="about" className="mb-3">
        <Tab eventKey="about" title={`About ${member.knownAs}`}>
          <form autoComplete="off" onSubmit={handleSubmit(onSubmit)}>
            <h4 className="mt-2">Description</h4>
            <textarea
              className="form-control"
              rows={6}
              defaultValue={member.introduction}
              {...register("description", {})}
            ></textarea>
            <h4 className="mt-2">Interests</h4>
            <textarea
              className="form-control"
              rows={6}
              defaultValue={member.interests}
              {...register("lookingFor", {})}
            ></textarea>
            <div className="d-flex flew-row align-items-center mt-4">
              <label>City: </label>
              <input
                type="text"
                defaultValue={member.city}
                className="form-control mx-2"
                {...register("city", {})}
              />
              <label>Country: </label>
              <input
                type="text"
                defaultValue={member.country}
                className="form-control mx-2"
                {...register("country", {})}
              />
            </div>
          </form>
        </Tab>
        <Tab eventKey="photos" title="Edit Photos">
          <p>Edit photos here</p>
        </Tab>
      </Tabs>
    );
  };

  return (
    <div className="row" style={{ padding: 30 }}>
      {member ? (
        <>
          <style>
            {`
            .img-thumbnail {
              margin: 25px;
              width: 85%;
              height: 85%;
            }
            .card-body {
              padding: 0 25px;
            }

            .card-footer {
              padding: 10px 15px;
              background-color: #FFF;
              border-top: none;
            }
          `}
          </style>
          <div className="col-4">
            <h1>Your profile</h1>
          </div>
          {isDirty ? (
            <div className="col-8">
              <div className="alert alert-info">
                <p>
                  <strong>Information:</strong>
                  You have made changes. Any unsaved changes will be lost.
                </p>
              </div>
            </div>
          ) : (
            <div className="col-8"></div>
          )}
          <div className="col-4">
            <div className="card">
              <img
                src={member.photoUrl || "../../assets/user.png"}
                alt={member.knownAs}
                className="card-img-top img-thumbnail"
                style={{ margin: 25, width: "85%", height: "85%" }}
              />
              <div
                style={{
                  paddingTop: 0,
                  paddingBottom: 0,
                  paddingLeft: 25,
                  paddingRight: 25,
                }}
              >
                <div>
                  <strong>Location: </strong>
                  <p>{member.country}</p>
                </div>
                <div>
                  <strong>Age: </strong>
                  <p>{member.age}</p>
                </div>
                {member.lastActive ? (
                  <div>
                    <strong>Last Active: </strong>
                    <p>{new Date(member.lastActive).toDateString()}</p>
                  </div>
                ) : null}
                {member.created ? (
                  <div>
                    <strong>Member since: </strong>
                    <p>{new Date(member.created).toDateString()}</p>
                  </div>
                ) : null}
              </div>
              <div
                style={{
                  paddingTop: 10,
                  paddingBottom: 10,
                  paddingLeft: 15,
                  paddingRight: 15,
                  borderTop: "none",
                  backgroundColor: "#FFF",
                }}
              >
                <button
                  type="submit"
                  onClick={handleSubmit(onSubmit)}
                  className="btn btn-success col-12"
                  disabled={!isDirty}
                >
                  Save changes
                </button>
              </div>
            </div>
          </div>
          <div className="col-8">{renderTabs(member)}</div>
        </>
      ) : null}
    </div>
  );
}
