// client/src/app/members/member-edit/member-edit.component.ts
import { Component, HostListener, OnInit, ViewChild } from '@angular/core';
import { NgForm } from '@angular/forms';
import { ToastrService } from 'ngx-toastr';
import { take } from 'rxjs';
import { Member } from 'src/app/_models/member';
import { User } from 'src/app/_models/user';
import { AccountService } from 'src/app/_services/account.service';
import { MembersService } from 'src/app/_services/members.service';

@Component({
  selector: 'app-member-edit',
  templateUrl: './member-edit.component.html',
  styleUrls: ['./member-edit.component.css'],
})
export class MemberEditComponent implements OnInit {
  @ViewChild('editForm') editForm: NgForm | undefined;
  @HostListener('window:beforeunload', ['$event']) unloadNotification(
    $event: any
  ) {
    if (this.editForm?.dirty) {
      $event.returnValue = true;
    }
  }
  member: Member | undefined;
  user: User | null = null;

  constructor(
    private accountService: AccountService,
    private memberService: MembersService,
    private toastr: ToastrService
  ) {
    this.accountService.currentUser$.pipe(take(1)).subscribe({
      next: (user) => (this.user = user),
    });
  }

  ngOnInit(): void {
    this.loadMember();
  }

  loadMember() {
    if (!this.user) return;

    this.memberService.getMember(this.user.username).subscribe({
      next: (member) => (this.member = member),
    });
  }

  updateMember() {
    this.memberService.updateMember(this.editForm?.value).subscribe({
      next: _ => {
        this.toastr.success('Profile updated successfully');
        this.editForm?.reset(this.member);
      }
    })
  }
}

<div class="row" *ngIf="member">
  <div class="col-4">
    <h1>Your profile</h1>
  </div>
  <div class="col-8">
    <div class="alert alert-info pb-0" *ngIf="editForm.dirty">
      <p><strong>Information: </strong>You have made changes. Any unsaved changes will be lost</p>
    </div>
  </div>
  <div class="col-4">
    <div class="card">
      <img src="{{member.photoUrl || './assets/user.png'}}" alt="{{member.knownAs}}" class="card-img-top img-thumbnail">
      <div class="card-body">
        <div>
          <strong>Location: </strong>
          <p>{{member.city}}, {{member.country}}</p>
        </div>
        <div>
          <strong>Age: </strong>
          <p>{{member.age}}</p>
        </div>
        <div>
          <strong>Last active: </strong>
          <p>{{member.lastActive}}</p>
        </div>
        <div>
          <strong>Member since: </strong>
          <p>{{member.created}}</p>
        </div>
      </div>
      <div class="card-footer">
        <button type="submit" [disabled]="!editForm.dirty" form="editForm" class="btn btn-success col-12">Save
          changes</button>
      </div>

    </div>
  </div>
  <div class="col-8">
    <tabset class="member-tabset">
      <tab heading="About {{member.knownAs}}">
        <form #editForm="ngForm" id="editForm" (ngSubmit)="updateMember()">
          <h4 class="mt-2">Description</h4>
          <textarea class="form-control" [(ngModel)]="member.introduction" name="introduction" rows="6"></textarea>
          <!-- <h4 class="mt-2">Looking for</h4>
          <textarea class="form-control" [(ngModel)]="member.interests" name="lookingFor" rows="6"></textarea> -->
          <h4 class="mt-2">Interests</h4>
          <textarea class="form-control" [(ngModel)]="member.interests" name="interests" rows="6"></textarea>
          <h4 class="mt-2">Location Details:</h4>
          <div class="d-flex flew-row align-items-center">
            <label for="city">City: </label>
            <input type="text" [(ngModel)]="member.city" name="city" [value]="member.city" class="form-control mx-2">
            <label for="country">Country: </label>
            <input type="text" [(ngModel)]="member.country" name="country" [value]="member.country" class="form-control mx-2">
          </div>
        </form>
      </tab>
      <tab heading="Edit photos">
        <p>Photo edit goes here</p>
      </tab>
    </tabset>
  </div>
</div>

// dating-app/src/components/Members/MemberEdit.tsx
import { Tab, Tabs } from "react-bootstrap";
import { Member } from "../../models/Member";
import { useLocation } from "react-router-dom";
import { useCallback, useEffect, useState } from "react";
import { useGetMember } from "./hooks";
import { useForm } from "react-hook-form";

interface EditFormData {
  city: string;
  country: string;
  description: string;
  lookingFor: string;
}

export default function MemberEdit() {
  const { state } = useLocation();
  const { username } = state;

  const {
    register,
    handleSubmit,
    formState: { isDirty },
  } = useForm<EditFormData>();

  const [member, setMember] = useState<Member>();

  const { getMember } = useGetMember(username);

  const memberHookFetch = useCallback(async () => {
    const memberHook = await getMember();
    setMember(memberHook);
    console.log("hook: ", memberHook);
    setMember(memberHook);
  }, [getMember]);

  useEffect(() => {
    memberHookFetch();
  }, [memberHookFetch]);

  const onSubmit = useCallback((formValues: any) => {
    console.log("values: ", formValues);
  }, []);

  if (!username) return <div></div>;

  const renderTabs = (member: Member) => {
    return (
      <Tabs defaultActiveKey="about" className="mb-3">
        <Tab eventKey="about" title={`About ${member.knownAs}`}>
          <form autoComplete="off" onSubmit={handleSubmit(onSubmit)}>
            <h4 className="mt-2">Description</h4>
            <textarea
              className="form-control"
              rows={6}
              defaultValue={member.introduction}
              {...register("description", {})}
            ></textarea>
            <h4 className="mt-2">Interests</h4>
            <textarea
              className="form-control"
              rows={6}
              defaultValue={member.interests}
              {...register("lookingFor", {})}
            ></textarea>
            <div className="d-flex flew-row align-items-center mt-4">
              <label>City: </label>
              <input
                type="text"
                defaultValue={member.city}
                className="form-control mx-2"
                {...register("city", {})}
              />
              <label>Country: </label>
              <input
                type="text"
                defaultValue={member.country}
                className="form-control mx-2"
                {...register("country", {})}
              />
            </div>
          </form>
        </Tab>
        <Tab eventKey="photos" title="Edit Photos">
          <p>Edit photos here</p>
        </Tab>
      </Tabs>
    );
  };

  return (
    <div className="row" style={{ padding: 30 }}>
      {member ? (
        <>
          <style>
            {`
            .img-thumbnail {
              margin: 25px;
              width: 85%;
              height: 85%;
            }
            .card-body {
              padding: 0 25px;
            }

            .card-footer {
              padding: 10px 15px;
              background-color: #FFF;
              border-top: none;
            }
          `}
          </style>
          <div className="col-4">
            <h1>Your profile</h1>
          </div>
          {isDirty ? (
            <div className="col-8">
              <div className="alert alert-info">
                <p>
                  <strong>Information:</strong>
                  You have made changes. Any unsaved changes will be lost.
                </p>
              </div>
            </div>
          ) : (
            <div className="col-8"></div>
          )}
          <div className="col-4">
            <div className="card">
              <img
                src={member.photoUrl || "../../assets/user.png"}
                alt={member.knownAs}
                className="card-img-top img-thumbnail"
                style={{ margin: 25, width: "85%", height: "85%" }}
              />
              <div
                style={{
                  paddingTop: 0,
                  paddingBottom: 0,
                  paddingLeft: 25,
                  paddingRight: 25,
                }}
              >
                <div>
                  <strong>Location: </strong>
                  <p>{member.country}</p>
                </div>
                <div>
                  <strong>Age: </strong>
                  <p>{member.age}</p>
                </div>
                {member.lastActive ? (
                  <div>
                    <strong>Last Active: </strong>
                    <p>{new Date(member.lastActive).toDateString()}</p>
                  </div>
                ) : null}
                {member.created ? (
                  <div>
                    <strong>Member since: </strong>
                    <p>{new Date(member.created).toDateString()}</p>
                  </div>
                ) : null}
              </div>
              <div
                style={{
                  paddingTop: 10,
                  paddingBottom: 10,
                  paddingLeft: 15,
                  paddingRight: 15,
                  borderTop: "none",
                  backgroundColor: "#FFF",
                }}
              >
                <button
                  type="submit"
                  onClick={handleSubmit(onSubmit)}
                  className="btn btn-success col-12"
                  disabled={!isDirty}
                >
                  Save changes
                </button>
              </div>
            </div>
          </div>
          <div className="col-8">{renderTabs(member)}</div>
        </>
      ) : null}
    </div>
  );
}
