// DatingApp.SPA/src/app/members/member-detail/member-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { User } from '../../_models/User';
import { UserService } from '../../_services/user.service';
import { AlertifyService } from '../../_services/alertify.service';
import { ActivatedRoute } from '@angular/router';
import { NgxGalleryOptions, NgxGalleryImage, NgxGalleryAnimation } from 'ngx-gallery';

@Component({
  selector: 'app-member-detail',
  templateUrl: './member-detail.component.html',
  styleUrls: ['./member-detail.component.css']
})
export class MemberDetailComponent implements OnInit {
  user: User;
  galleryOptions: NgxGalleryOptions[];
  galleryImages: NgxGalleryImage[];

  constructor(private userService: UserService, private alertify: AlertifyService, private route: ActivatedRoute) { }

  ngOnInit() {
    this.route.data.subscribe(data => {
      this.user = data['user'];
    });

    this.galleryOptions = [
      {
        width: '500px',
        height: '500px',
        imagePercent: 100,
        thumbnailsColumns: 4,
        imageAnimation: NgxGalleryAnimation.Slide,
        preview: false
      }
    ];

    this.galleryImages = this.getImages();
  }

  getImages() {
    const imageUrls = [];
    for (let i = 0; i < this.user.photos.length; i++) {
      imageUrls.push({
        small: this.user.photos[i].url,
        medium: this.user.photos[i].url,
        big: this.user.photos[i].url,
        description: this.user.photos[i].description
      });
    }
    return imageUrls;
  }

}

<div class="container">
  <div class="row">
    <h1>{{user.knownAs}}'s Profile</h1>
  </div>

  <div class="row">
    <div class="col-sm-4">
      <div class="panel panel-default">
        <img class="profile-image thumbnail" src="{{user.photoUrl || '../../../../../assets/user.png'}}" alt="{{user.knownAs}}">
        <div class="panel-body">
          <div>
            <strong>Location:</strong>
            <p>{{user.city}}, {{user.country}}</p>
          </div>

          <div>
            <strong>Age:</strong>
            <p>{{user.age}}</p>
          </div>

          <div>
            <strong>Last Active:</strong>
            <p>{{user.lastactive | timeAgo}}</p>
          </div>

          <div>
            <strong>Member Since:</strong>
            <p>{{user.created | date}}</p>
          </div>
        </div>

        <div class="panel-footer">
          <div class="btn-group-justified">
            <div class="btn-group">
              <button class="btn btn-primary">Like</button>
            </div>
            <div class="btn-group">
              <button class="btn btn-success">Message</button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-8">
      <div class="tab-panel">
          <tabset class="member-tabset">
              <tab heading="About {{user.knownAs}}">
                <h4>Description</h4>
                <p>{{user.introduction}}</p>
                <h4>Looking for:</h4>
                <p>{{user.lookingFor}}</p>
              </tab>
      
              <tab heading="Interests">
                <h4>Description</h4>
                <p>{{user.interests}}</p>
              </tab>
      
              <tab heading="Photos">
                <ngx-gallery [options]="galleryOptions" [images]="galleryImages"></ngx-gallery>
              </tab>
      
              <tab heading="Messages">
                <p>Messages go here</p>
              </tab>
            </tabset>
      </div>
      
    </div>
  </div>

</div>

// dating-app/src/components/Members/MemberDetail.tsx
import { useCallback, useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { Member } from "../../models/Member";
import { Tab, Tabs } from "react-bootstrap";
import PhotoGallery from "./components/PhotoGallery/PhotoGallery";
import { useGetMember } from "./hooks";

export default function MemberDetail() {
  const { username } = useParams();

  const [member, setMember] = useState<Member>();
  const { getMember: getMemberHook } = useGetMember(username);

  const memberHookFetch = useCallback(async () => {
    const memberHook = await getMemberHook();
    setMember(memberHook);
    console.log("hook: ", memberHook);
  }, [getMemberHook]);

  useEffect(() => {
    memberHookFetch();
  }, [memberHookFetch]);

  if (!username) {
    return <div>Member not found....</div>;
  }

  const renderTabs = (member: Member) => {
    return (
      <Tabs defaultActiveKey="about" className="mb-3">
        <Tab eventKey="about" title={`About ${member.knownAs}`}>
          <h4>Description</h4>
          <p>{member.introduction}</p>
          <h4>Looking for</h4>
          <p>{member.interests}</p>
        </Tab>
        <Tab eventKey="profile" title="Interests">
          <h4>Interests</h4>
          <p>{member.interests}</p>
        </Tab>
        <Tab eventKey="photo" title="Photos">
          <PhotoGallery photos={member.photos} />
        </Tab>
        <Tab eventKey="messages" title="Messages">
          Tab content for Messages
        </Tab>
      </Tabs>
    );
  };

  return (
    <div className="row" style={{ paddingLeft: 30, paddingTop: 25 }}>
      {member ? (
        <>
          <div className="col-4">
            <div className="card">
              <img
                src={member.photoUrl || "../../assets/user.png"}
                alt={member.knownAs}
                className="card-img-top img-thumbnail"
                style={{ margin: 25, width: "85%", height: "85%" }}
              />
              <div
                style={{
                  paddingTop: 0,
                  paddingBottom: 0,
                  paddingLeft: 25,
                  paddingRight: 25,
                }}
              >
                <div>
                  <strong>Location: </strong>
                  <p>{member.country}</p>
                </div>
                <div>
                  <strong>Age: </strong>
                  <p>{member.age}</p>
                </div>
                {member.lastActive ? (
                  <div>
                    <strong>Last Active: </strong>
                    <p>{new Date(member.lastActive).toDateString()}</p>
                  </div>
                ) : null}
                {member.created ? (
                  <div>
                    <strong>Member since: </strong>
                    <p>{new Date(member.created).toDateString()}</p>
                  </div>
                ) : null}
              </div>
              <div
                style={{
                  paddingTop: 10,
                  paddingBottom: 10,
                  paddingLeft: 15,
                  paddingRight: 15,
                  borderTop: "none",
                  backgroundColor: "#FFF",
                }}
              >
                <div className="btn-group d-flex">
                  <button className="btn btn-primary">Like</button>
                  <button className="btn btn-success">Messages</button>
                </div>
              </div>
            </div>
          </div>
          <div className="col-8">{renderTabs(member)}</div>
        </>
      ) : null}
    </div>
  );
}
